USE [master]
GO

/****** Object:  Database [AGROTIS]    Script Date: 13/03/2022 09:44:12 ******/
CREATE DATABASE [AGROTIS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AGROTIS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\AGROTIS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AGROTIS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\AGROTIS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [AGROTIS] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AGROTIS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AGROTIS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AGROTIS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AGROTIS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AGROTIS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AGROTIS] SET ARITHABORT OFF 
GO

ALTER DATABASE [AGROTIS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AGROTIS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AGROTIS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AGROTIS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AGROTIS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AGROTIS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AGROTIS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AGROTIS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AGROTIS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AGROTIS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AGROTIS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AGROTIS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AGROTIS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AGROTIS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AGROTIS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AGROTIS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AGROTIS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AGROTIS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AGROTIS] SET  MULTI_USER 
GO

ALTER DATABASE [AGROTIS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AGROTIS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AGROTIS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AGROTIS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AGROTIS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AGROTIS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AGROTIS] SET  READ_WRITE 
GO

USE [AGROTIS]
GO

/****** Object:  Table [dbo].[CLIENTE]    Script Date: 13/03/2022 09:51:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [AGROTIS]
GO

/****** Object:  Table [dbo].[CLIENTE]    Script Date: 13/03/2022 18:23:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENTE](
	[CDCLIENTE] [int] IDENTITY(1,1) NOT NULL,
	[NMCLIENTE] [varchar](150) NULL,
	[NRCEP] [varchar](8) NULL,
	[DSLOGRADOURO] [varchar](150) NULL,
	[DSBAIRRO] [varchar](150) NULL,
	[NMCIDADE] [varchar](150) NULL,
	[DSCOMPLEMENTO] [varchar](150) NULL,
	[UF] [varchar](2) NULL,
	[CDIBGE] [varchar](10) NULL,
 CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[CDCLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [AGROTIS]
GO

/****** Object:  Table [dbo].[PEDIDO]    Script Date: 13/03/2022 18:23:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PEDIDO](
	[NRPEDIDO] [int] NOT NULL,
	[CDCLIENTE] [int] NULL,
	[DTEMISSAO] [date] NULL,
	[VLPRECOTOTAL] [numeric](18, 2) NULL,
	[VLPESOTOTAL] [numeric](18, 3) NULL,
 CONSTRAINT [PK_PEDIDO] PRIMARY KEY CLUSTERED 
(
	[NRPEDIDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [AGROTIS]
GO

/****** Object:  Table [dbo].[PEDIDOITEM]    Script Date: 13/03/2022 18:24:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PEDIDOITEM](
	[NRPEDIDO] [int] NOT NULL,
	[CDPRODUTO] [int] NOT NULL,
	[QTPRODUTO] [int] NULL,
	[VLUNITARIO] [numeric](18, 2) NULL,
 CONSTRAINT [PK_PEDIDOITEM] PRIMARY KEY CLUSTERED 
(
	[NRPEDIDO] ASC,
	[CDPRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [AGROTIS]
GO

/****** Object:  Table [dbo].[PRODUTO]    Script Date: 13/03/2022 18:24:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUTO](
	[CDPRODUTO] [int] IDENTITY(1,1) NOT NULL,
	[DSPRODUTO] [varchar](150) NULL,
	[VLPESOLIQ] [numeric](18, 3) NULL,
	[VLUNITARIO] [numeric](18, 3) NULL,
 CONSTRAINT [PK_PRODUTO] PRIMARY KEY CLUSTERED 
(
	[CDPRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



